R NPTEL Week 05
Name: Aditi Gawari
Roll no: 23102A0025

Missing Data

In [1]:
x = NA
is.na(x)

[1] TRUE

In [2]:
x = c(11, NA, 13, NA)
is.na(x)

[1] FALSE  TRUE FALSE  TRUE

How to work with missing data

In [3]:
x = c(11, NA, 13, NA)

In [4]:
mean(x)

[1] NA

In [5]:
mean(x, na.rm = TRUE)

[1] 12

NA versus NULL

In [7]:
x = c(11, NA, 13, NA)
x

[1] 11 NA 13 NA

In [8]:
which(is.na(x))

[1] 2 4

In [9]:
sum(is.na(x))

[1] 2

In [10]:
complete.cases(x)

[1]  TRUE FALSE  TRUE FALSE

In [11]:
y = na.omit(x)
y

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

In [14]:
mean(x)
mean(y)

[1] NA

[1] 12

Control Structures in R

Conditional execution: if()

In [15]:
x = 5

In [16]:
if(x>4) x*3

[1] 15

In [17]:
x = 3

In [18]:
if(x>4) x*3

In [19]:
x = 5

In [20]:
if(x>4) {x*3}

[1] 15

In [21]:
x = 3

In [22]:
if (x>4) {x*3}

In [24]:
x = 6

In [25]:
if (x > 3) {
  print("The value is more than 3")
}

[1] "The value is more than 3"

In [26]:
x = 2

In [28]:
if (x>3) {
  print("The value is more than 3")
}

Conditional execution: if else()

In [29]:
x = 5

In [30]:
if ( x==3) {x=x-1} else {x=2*x}
x

[1] 10

In [31]:
x = 3

In [32]:
if ( x==3) {x=x-1} else {x=2*x}
x

[1] 2

In [33]:
x = 6

In [34]:
if (x>3) {
  print("The value is more than 3")
} else {
  print("The value is less than 3")
}

[1] "The value is more than 3"

In [35]:
x = 2

In [36]:
if (x>3) {
  print("The value is more than 3")
} else {
  print("The value is less than 3")
}

[1] "The value is less than 3"

Conditional execution: Nested if else if()

In [37]:
x = 5

In [39]:
if (x==3) {
  x = x-1
} else if (x<3) {
  x = x+5
} else {x = 2*x}
x

[1] 10

In [40]:
x = 2

In [41]:
if (x==3) {
  x = x-1
} else if (x<3) {
  x = x+5
} else {x = 2*x}
x

[1] 7

In [42]:
x = 3

In [43]:
if (x==3) {
  x = x-1
} else if (x<3) {
  x = x+5
} else {x = 2*x}
x

[1] 2

Conditional execution: ifelse()

In [44]:
x = 1:10
x

 [1]  1  2  3  4  5  6  7  8  9 10

In [45]:
ifelse(x<6, x^2, x+1)

 [1]  1  4  9 16 25  7  8  9 10 11

In [46]:
x = c(7, 9, 8, 4)

In [47]:
ifelse(x%%2 == 0, "even number", "odd number")

[1] "odd number"  "odd number"  "even number" "even number"

Conditional execution:  switch()

In [48]:
switch(2, "apple", "banana", "orange")

[1] "banana"

In [49]:
switch(1, "apple", "banana", "orange")

[1] "apple"

In [50]:
switch("colour", "colour" = "blue", "gender" = "male", "volume" = 50)

[1] "blue"

In [51]:
switch("volume", "colour" = "blue", "gender" = "male", "volume" = 50)

[1] 50

In [52]:
switch(4, "apple", "banana", "orange")

In [53]:
switch("size", "colour" = "blue", "gender" = "male", "volume" = 50)

In [ ]:
Conditional execution: which()

In [54]:
x = c(10, 15, 8, 14, 6, 12)
x

[1] 10 15  8 14  6 12

In [55]:
which(x == 14)

[1] 4

In [56]:
which(x!=12)

[1] 1 2 3 4 5

In [57]:
which(x>10)

[1] 2 4 6

In [59]:
x = matrix(nrow=3, ncol = 3, data=1:9)
x

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

In [60]:
which.min(x)

[1] 1

In [61]:
which.max(x)

[1] 9

In [62]:
which(x%%2 == 1)

[1] 1 3 5 7 9

In [63]:
which(x%%2 == 1, arr.ind = TRUE)

     row col
[1,] 1   1
[2,] 3   1
[3,] 2   2
[4,] 1   3
[5,] 3   3